# AdaPT sweep: 2 datasets x 3 models x 6 multipliers x (eval-only, retrained)

Writes one row per `(dataset, model, multiplier, retrained_epochs)` to `results/runs.csv` and a per-run confusion matrix to `results/confusion_matrices/<dataset>/<model>_<multiplier>_e<epochs>.npy`.

Models come from `chenyaofo/pytorch-cifar-models`, which has pretrained weights for CIFAR-10 and CIFAR-100. `wrap_with_adapt` swaps every `nn.Conv2d` in-place for `AdaPT_Conv2d`, so the approximate kernel runs in every conv layer.

Each `(dataset, model)` also gets one `fp32` reference row — the raw float model with no quantization or approximation. It is the fp32→int8 anchor for the architecture comparison (TransAxx already records the matching `fp32` rows for the ViTs); being a plain float eval, it has no retrained variant.

Re-running is safe: rows already in the CSV are skipped. To recompute everything from scratch (e.g. after changing the recipe or LUTs), set `FRESH = True` in the config cell.

In [1]:
import csv, gc, os, time, uuid
from pathlib import Path
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import transforms as T
from torchvision.datasets import CIFAR10, CIFAR100, ImageFolder  # ImageFolder: bring-your-own-dataset example in make_loaders
from tqdm import tqdm

from adapt.approx_layers.axx_layers import AdaPT_Conv2d
from adapt.references.classification.train import train_one_epoch
from pytorch_quantization import nn as quant_nn, calib

torch.set_num_threads(40)
%env OMP_PLACES=cores
%env OMP_PROC_BIND=close
%env OMP_WAIT_POLICY=active

env: OMP_PLACES=cores
env: OMP_PROC_BIND=close
env: OMP_WAIT_POLICY=active

## LUT-level error metrics

A quick sanity table before the sweep: a pure-numpy diff of each multiplier's LUT against `mul8s_acc`. It lets you eyeball whether the headers under `adapt/cpu-kernels/axx_mults/` match what you expect.

In [2]:
import re
# absolute path to AdaPT's JIT kernel header dir (cwd is /work/notebooks now)
AXX_DIR = Path("/workspace/adapt/adapt/cpu-kernels/axx_mults")

def load_lut(name):
    text = (AXX_DIR / f"{name}.h").read_text()
    nums = re.findall(r"-?\d+", text.split("{", 1)[1])
    return np.array(nums, dtype=np.int16).reshape(256, 256)

def signed_view(lut):
    perm = np.r_[0:128, -128:0]
    order = np.argsort(perm)
    return lut[np.ix_(order, order)]

def lut_metrics(name, ref="mul8s_acc"):
    L = signed_view(load_lut(name)).astype(np.int32)
    R = signed_view(load_lut(ref)).astype(np.int32)
    err = L - R
    abs_err = np.abs(err).astype(np.float64)
    nonzero = R != 0
    rel = np.divide(abs_err, np.abs(R), out=np.zeros_like(abs_err), where=nonzero)
    return {
        "name": name,
        "ER":   float((err != 0).mean()),
        "MAE":  float(abs_err.mean()),
        "WCE":  int(np.abs(err).max()),
        "MSE":  float((err.astype(np.float64) ** 2).mean()),
        "MRED": float(rel[nonzero].mean()),
        "NMED": float(abs_err.mean() / (127 * 127)),
        "bias": float(err.mean()),
    }

_lut_names = [f"mul8s_fpga_ish_{i}" for i in range(1, 6)]
pd.DataFrame([lut_metrics(n) for n in _lut_names])

,name,ER,MAE,WCE,MSE,MRED,NMED,bias
0,mul8s_fpga_ish_1,0.334229,49.149414,714,19740.25,0.013288,0.003047,0.0
1,mul8s_fpga_ish_2,0.314453,19.818359,202,2196.25,0.008061,0.001229,0.0
2,mul8s_fpga_ish_3,0.288086,18.137695,170,2024.25,0.007219,0.001125,0.0
3,mul8s_fpga_ish_4,0.261719,17.075195,168,2040.25,0.006552,0.001059,0.0
4,mul8s_fpga_ish_5,0.226562,17.000000,168,2039.50,0.006434,0.001054,0.0

## Sweep config

**Models / datasets / parameters are set in `0_configure_sweeps.ipynb`** (edit there, Run All,
then re-run this notebook, since the cell below just reads its `sweep_config.json`). Only `FRESH`
lives here, because it deletes results. Results path is the `results/` volume mount, which
on the host maps to `docker/results/adapt/`.

In [3]:
import json as _json

# What to sweep comes from 0_configure_sweeps' manifest (EDIT THERE, not here,
# since this file is the single place models/datasets/params are defined). The literals
# below are only fallbacks for when the manifest hasn't been written yet.
_cfg_all = _json.loads(Path("sweep_config.json").read_text()) \
           if Path("sweep_config.json").exists() else {}
_cfg = _cfg_all.get("adapt", {})
DATASETS       = _cfg.get("datasets", ["cifar10", "cifar100"])
MODELS         = _cfg.get("models", ["resnet20", "resnet56", "vgg11_bn"])
RETRAIN_EPOCHS = _cfg.get("retrain_epochs", 3)
BATCH_SIZE     = _cfg.get("batch_size", 128)
CALIB_BATCHES  = _cfg.get("calib_batches", 2)
# Local user-provided models (docker/models/<name>.py + weights, mounted at ../models),
# registered in 0_configure_sweeps. Each runs only on its declared dataset.
LOCAL_MODELS   = {n: s for n, s in _cfg_all.get("local_models", {}).items()
                  if s.get("framework") == "adapt"}

# Multipliers come from 0_build_multipliers' manifest (define once, sweep everywhere).
# mul8s_exact is the generator's exact twin of the mul8s_acc baseline, so we keep acc
# and drop the duplicate. Falls back to the fixed list if the manifest is not built yet.
_manifest = Path("../luts/multipliers.json")
if _manifest.exists():
    _built = _json.loads(_manifest.read_text())["multipliers"]
    MULTS = [m for m in _built if m != "mul8s_exact"] + ["mul8s_acc"]
else:
    MULTS = [f"mul8s_fpga_ish_{i}" for i in range(1, 6)] + ["mul8s_acc"]

# FRESH = False -> resume: rows already in runs.csv are skipped, so you can
#                  interrupt and re-run safely. NOTE: it only checks whether a
#                  row exists, not whether it is up to date -- if you change the
#                  recipe / LUTs / calibration it will NOT recompute existing rows.
# FRESH = True  -> wipe runs.csv + confusion_matrices/ (and legacy runs/) first and
#                  recompute the whole matrix from scratch.
FRESH = False

# Jupyter roots at /work, and this notebook lives in /work/notebooks, so results go to
# /work/results/adapt (compose mounts ./results -> /work/results).
RESULTS_DIR = Path("../results/adapt")
RESULTS_DIR.mkdir(parents=True, exist_ok=True)
CSV_PATH = RESULTS_DIR / "runs.csv"
COLS = ["run_id", "timestamp", "dataset", "model", "multiplier",
        "retrained_epochs", "top1", "top5", "n_samples", "runtime_s", "notes"]

if FRESH:
    import shutil
    CSV_PATH.unlink(missing_ok=True)
    for _d in (RESULTS_DIR / "confusion_matrices", RESULTS_DIR / "runs"):
        shutil.rmtree(_d, ignore_errors=True)
    print("FRESH=True -> cleared runs.csv, confusion_matrices/ and legacy runs/")

print(f"Matrix size: {len(DATASETS)} x {len(MODELS)} x {len(MULTS)} x 2 = "
      f"{len(DATASETS)*len(MODELS)*len(MULTS)*2} rows")
if LOCAL_MODELS:
    print("+ local models: " + ", ".join(f"{n} (on {s['dataset']} only)"
                                          for n, s in LOCAL_MODELS.items()))

Matrix size: 2 x 3 x 9 x 2 = 108 rows

## Data loaders

A small `DATASETS` registry maps each dataset name to its normalisation stats, class count, and a `build(root, transform)` that returns the `(train, test)` datasets. `make_loaders` then just looks the name up. The CIFAR entries use the standard per-channel normalisation `chenyaofo/pytorch-cifar-models` was trained with. Adding a dataset (a torchvision one, or your own `ImageFolder`) is one entry here plus allowing the name in `0_configure_sweeps`' validator, as shown by the commented `myset` example. Calibration set is every 10th sample of train (10% subset, same convention as the upstream notebook).

In [4]:
# ---- Dataset registry -------------------------------------------------------
# One entry per dataset: normalisation stats, class count, and a build(root, transform)
# that returns the (train, test) torch Datasets. To ADD a dataset, add an entry here and
# allow its name in 0_configure_sweeps' validator -- nothing else in this notebook needs
# to change. Anything torchvision can build, or your own ImageFolder, drops in this way
# (see the commented "myset" example). Data lives under /workspace/datasets, bind-mounted
# from docker/datasets, so it persists across rebuilds and can be staged offline.
def _torchvision_cifar(cls):
    """Factory for the CIFAR-family API: cls(root, train=bool, download, transform)."""
    def build(root, transform):
        train = cls(root=root, train=True,  download=True, transform=transform)
        test  = cls(root=root, train=False, download=True, transform=transform)
        return train, test
    return build

DATASETS = {
    "cifar10":  {"mean": (0.4914, 0.4822, 0.4465), "std": (0.2471, 0.2435, 0.2616),
                 "n_classes": 10,  "build": _torchvision_cifar(CIFAR10)},
    "cifar100": {"mean": (0.5071, 0.4867, 0.4408), "std": (0.2675, 0.2565, 0.2761),
                 "n_classes": 100, "build": _torchvision_cifar(CIFAR100)},

    # ---- Example: bring-your-own dataset (uncomment + allow "myset" in the validator
    # of 0_configure_sweeps to use). Put the images under
    #   docker/datasets/myset_data/{train,test}/<class_name>/*.jpg
    # and ImageFolder reads the class labels straight from the folder names. Use real
    # per-channel mean/std for your data; (0.5, 0.5, 0.5) is just a placeholder.
    # "myset": {
    #     "mean": (0.5, 0.5, 0.5), "std": (0.5, 0.5, 0.5), "n_classes": 10,
    #     "build": lambda root, tf: (ImageFolder(f"{root}/train", transform=tf),
    #                                ImageFolder(f"{root}/test",  transform=tf)),
    # },
}

def make_loaders(dataset, batch_size=BATCH_SIZE):
    info = DATASETS[dataset]
    tf = T.Compose([T.ToTensor(), T.Normalize(info["mean"], info["std"])])
    # absolute path (cwd is /work/notebooks now); bind-mounted from docker/datasets.
    root = f"/workspace/datasets/{dataset}_data"
    train, test = info["build"](root, tf)
    val = DataLoader(test, batch_size=batch_size, num_workers=0,
                     drop_last=True, pin_memory=False)
    evens = list(range(0, len(train), 10))
    cal = DataLoader(torch.utils.data.Subset(train, evens),
                     batch_size=batch_size, shuffle=False,
                     num_workers=0, drop_last=True, pin_memory=False)
    return val, cal

## Model builder + AdaPT wrap

`build_model` pulls pretrained weights from the chenyaofo hub. `wrap_with_adapt` walks the module tree and swaps every `nn.Conv2d` for an `AdaPT_Conv2d` of the same shape, copying weights/bias across. Each new `AdaPT_Conv2d` JIT-compiles its C++ kernel on first instantiation per `axx_mult`, which is the slow first iteration of the sweep.

In [5]:
def build_model(name, dataset):
    hub_id = f"{dataset}_{name}"
    return torch.hub.load("chenyaofo/pytorch-cifar-models", hub_id, pretrained=True)

MODELS_DIR = Path("../models")   # docker/models on the host, /work/models in-container

def build_local_model(name):
    """Import docker/models/<name>.py and call its build_model(). The .py owns
    everything model-specific (architecture, weight loading, output selection),
    so this notebook never needs editing for a new model (see ../models/README.md)."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(name, (MODELS_DIR / f"{name}.py").resolve())
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.build_model()

def wrap_with_adapt(model, axx_mult):
    """Recursively replace nn.Conv2d -> AdaPT_Conv2d, copying weights/bias."""
    for name, module in model.named_children():
        if isinstance(module, nn.Conv2d) and not isinstance(module, AdaPT_Conv2d):
            new = AdaPT_Conv2d(
                module.in_channels, module.out_channels, module.kernel_size,
                stride=module.stride, padding=module.padding,
                dilation=module.dilation, groups=module.groups,
                bias=module.bias is not None, padding_mode=module.padding_mode,
                axx_mult=axx_mult,
            )
            new.weight.data.copy_(module.weight.data)
            if module.bias is not None:
                new.bias.data.copy_(module.bias.data)
            setattr(model, name, new)
        else:
            wrap_with_adapt(module, axx_mult)
    return model

## Calibration, evaluation, finetune helpers

In [6]:
def collect_stats(model, loader, num_batches):
    for _, m in model.named_modules():
        if isinstance(m, quant_nn.TensorQuantizer):
            if m._calibrator is not None:
                m.disable_quant(); m.enable_calib()
            else:
                m.disable()
    with torch.no_grad():
        for i, (img, _) in enumerate(loader):
            model(img.cpu())
            if i >= num_batches:
                break
    for _, m in model.named_modules():
        if isinstance(m, quant_nn.TensorQuantizer):
            if m._calibrator is not None:
                m.enable_quant(); m.disable_calib()
            else:
                m.enable()

def compute_amax(model, **kwargs):
    for _, m in model.named_modules():
        if isinstance(m, quant_nn.TensorQuantizer):
            if m._calibrator is not None:
                if isinstance(m._calibrator, calib.MaxCalibrator):
                    m.load_calib_amax()
                else:
                    m.load_calib_amax(**kwargs)
    model.cpu()

def calibrate(model, calib_loader):
    with torch.no_grad():
        collect_stats(model, calib_loader, num_batches=CALIB_BATCHES)
        compute_amax(model, method="percentile", percentile=99.99)

def evaluate(model, loader, n_classes):
    model.eval()
    correct = top5 = total = 0
    cm = np.zeros((n_classes, n_classes), dtype=np.int64)
    t0 = time.time()
    with torch.no_grad():
        for img, lbl in tqdm(loader, total=len(loader), leave=False):
            out = model(img)
            _, p5 = out.topk(5, dim=1)
            p1 = p5[:, 0]
            total += lbl.size(0)
            correct += (p1 == lbl).sum().item()
            top5 += (p5 == lbl.unsqueeze(1)).any(dim=1).sum().item()
            for t, p in zip(lbl.numpy(), p1.numpy()):
                cm[t, p] += 1
    dt = time.time() - t0
    return 100 * correct / total, 100 * top5 / total, total, dt, cm

def finetune(model, loader, epochs):
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
    for e in range(epochs):
        train_one_epoch(model, criterion, optimizer, loader, "cpu", e, 50)

In [7]:
def existing_keys():
    if not CSV_PATH.exists():
        return set()
    df = pd.read_csv(CSV_PATH)
    return {tuple(r) for r in df[["dataset", "model", "multiplier", "retrained_epochs"]]
                                  .itertuples(index=False, name=None)}

def append_row(row):
    new_file = not CSV_PATH.exists()
    with CSV_PATH.open("a", newline="") as f:
        w = csv.writer(f)
        if new_file:
            w.writerow(COLS)
        w.writerow([row.get(c, "") for c in COLS])

def cm_path(dataset, model_name, mult, retrained_epochs):
    """Human-readable, dataset-foldered confusion-matrix path, e.g.
    results/confusion_matrices/cifar100/resnet20_fpga_ish_1_e0.npy."""
    short = mult.replace("mul8s_", "")
    d = RESULTS_DIR / "confusion_matrices" / dataset
    d.mkdir(parents=True, exist_ok=True)
    return d / f"{model_name}_{short}_e{retrained_epochs}.npy"

def record(dataset, model_name, mult, retrained_epochs, top1, top5, n, dt, cm):
    rid = uuid.uuid4().hex[:12]
    np.save(cm_path(dataset, model_name, mult, retrained_epochs), cm)
    append_row({
        "run_id": rid,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "dataset": dataset, "model": model_name, "multiplier": mult,
        "retrained_epochs": retrained_epochs,
        "top1": f"{top1:.4f}", "top5": f"{top5:.4f}",
        "n_samples": n, "runtime_s": f"{dt:.1f}", "notes": "",
    })
    return rid

## Sweep

Outer loop: dataset; middle: model; inner: multiplier. For each cell:

1. Build a fresh chenyaofo model, wrap with this multiplier's AdaPT_Conv2d, calibrate.
2. Eval-only row → append (`retrained_epochs=0`) + save confusion matrix.
3. Finetune `RETRAIN_EPOCHS` epochs on the calib subset, re-evaluate → append + save.

Before the multiplier loop, each model also gets one `fp32` row — the raw float model evaluated with no AdaPT wrap and no quantization (the fp32→int8 anchor for the architecture comparison; no retrained variant).

Rows that are already present in `results/runs.csv` (matched on `dataset`, `model`, `multiplier`, `retrained_epochs`) are skipped, so you can interrupt and resume.

In [8]:
done = existing_keys()
print(f"{len(done)} rows already in CSV; will skip those.\n")

for dataset in DATASETS:
    val, cal = make_loaders(dataset)
    n_cls = DATASETS[dataset]["n_classes"]
    # local models join the matrix on their declared dataset only
    local_here = [n for n, s in LOCAL_MODELS.items() if s["dataset"] == dataset]
    for model_name in MODELS + local_here:
        # FP32 reference: the raw float model, no AdaPT wrap and no quantization.
        # This is the fp32->int8 anchor for the architecture comparison (mirrors the ViT fp32 rows TransAxx
        # already has). It is a plain float eval, not an approximate-multiplier run,
        # so it sits outside the multiplier loop and has no retrained variant.
        if (dataset, model_name, "fp32", 0) not in done:
            print(f"\n=== {dataset} / {model_name} / fp32 (float reference) ===")
            fb = (build_local_model(model_name) if model_name in local_here
                  else build_model(model_name, dataset)).eval()
            top1, top5, n, dt, cm = evaluate(fb, val, n_cls)
            rid = record(dataset, model_name, "fp32", 0, top1, top5, n, dt, cm)
            print(f"  fp32           top1={top1:.4f}  top5={top5:.4f}  ({dt:.1f}s)  run_id={rid}")
            del fb
            gc.collect()

        for mult in MULTS:
            need_eval     = (dataset, model_name, mult, 0) not in done
            need_retrain  = RETRAIN_EPOCHS > 0 and \
                            (dataset, model_name, mult, RETRAIN_EPOCHS) not in done
            if not (need_eval or need_retrain):
                print(f"[skip] {dataset}/{model_name}/{mult} — both rows present")
                continue

            print(f"\n=== {dataset} / {model_name} / {mult} ===")
            base = (build_local_model(model_name) if model_name in local_here
                    else build_model(model_name, dataset))
            m = wrap_with_adapt(base, mult).eval()
            calibrate(m, cal)

            if need_eval:
                top1, top5, n, dt, cm = evaluate(m, val, n_cls)
                rid = record(dataset, model_name, mult, 0, top1, top5, n, dt, cm)
                print(f"  eval-only      top1={top1:.4f}  top5={top5:.4f}  ({dt:.1f}s)  run_id={rid}")

            if need_retrain:
                finetune(m, cal, RETRAIN_EPOCHS)
                top1, top5, n, dt, cm = evaluate(m, val, n_cls)
                rid = record(dataset, model_name, mult, RETRAIN_EPOCHS,
                             top1, top5, n, dt, cm)
                print(f"  retrained({RETRAIN_EPOCHS}ep) top1={top1:.4f}  top5={top5:.4f}  ({dt:.1f}s)  run_id={rid}")

            del m, base
            gc.collect()

from IPython.display import FileLink, display

print("Done.")
print(f"Results saved under: {RESULTS_DIR.resolve()}\n")

# Live inventory of what the results folder holds right now.
n_rows = sum(1 for _ in open(CSV_PATH)) - 1
n_cm = len(list((RESULTS_DIR / "confusion_matrices").glob("*/*.npy")))
print(f"  runs.csv                                {n_rows} rows -- one per (dataset, model, multiplier, retrained/not)")
print(f"  confusion_matrices/<dataset>/<..>.npy   {n_cm} files  -- per-run confusion matrix (loaded by 3_multiplier_deepdive.ipynb)")

# Clickable link to the CSV, openable straight from this notebook.
print("\nOpen the results CSV:")
display(FileLink(str(CSV_PATH)))
pd.read_csv(CSV_PATH).tail(15)

123 rows already in CSV; will skip those.

Files already downloaded and verified
Files already downloaded and verified

=== cifar10 / resnet20 / mul8s_1kva ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
Creating extension directory /root/.cache/torch_extensions/py310_cpu/PyInit_conv2d_mul8s_1kva...
Emitting ninja build file /root/.cache/torch_extensions/py310_cpu/PyInit_conv2d_mul8s_1kva/build.ninja...
Building extension module PyInit_conv2d_mul8s_1kva...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)

[1/2] c++ -MMD -MF axx_conv2d.o.d -DTORCH_EXTENSION_NAME=PyInit_conv2d_mul8s_1kva -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DAXX_MULT=mul8s_1kva -march=native -fopenmp -O3 -c /workspace/adapt/adapt/cpu-kernels/axx_conv2d.cpp -o axx_conv2d.o
[2/2] c++ axx_conv2d.o -shared -lgomp -L/usr/local/lib/python3.10/dist-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o PyInit_conv2d_mul8s_1kva.so

Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
WARNING: Logging before flag parsing goes to stderr.
W0626 17:51:39.314865 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.315305 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.315788 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.316216 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.316764 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.316981 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.317367 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.317703 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.318006 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.318275 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.318585 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.318871 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.319145 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.319391 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.319650 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.319902 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.320168 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.320429 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.320698 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.320972 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.321248 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.321482 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.321720 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.321945 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.322176 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.322393 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.322619 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.322853 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.323088 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.323313 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.323533 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.323762 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.324003 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.324227 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.324460 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.324693 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.324926 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.325173 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.325556 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.325819 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.326051 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.326269 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:51:39.332830 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.333158 124414754996224 tensor_quantizer.py:239] Call .cuda() if running on GPU after loading calibrated amax.
W0626 17:51:39.333655 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.334044 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.334318 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.334556 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.334777 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.334989 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.335198 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.335406 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.335617 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.335827 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.336030 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.336241 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.336447 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.336672 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.336890 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.337125 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.337516 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.337754 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.337982 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.338217 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.338444 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.338661 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.338888 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.339109 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.339327 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.339548 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.339772 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.339987 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.340197 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.340461 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.340692 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.340913 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.341120 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.341326 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.341539 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.341753 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.341962 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.342171 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.342377 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.342592 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:51:39.342806 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
  0%|          | 0/78 [00:00<?, ?it/s][W LegacyTypeDispatch.h:74] Warning: AutoNonVariableTypeMode is deprecated and will be removed in 1.10 release. For kernel implementations please use AutoDispatchBelowADInplaceOrView instead, If you are looking for a user facing API to enable running your inference-only workload, please use c10::InferenceMode. Using AutoDispatchBelowADInplaceOrView in user code is under risk of producing silent wrong result in some edge cases. See Note [AutoDispatchBelowAutograd] for more details. (function operator())

  eval-only      top1=91.8470  top5=99.8197  (24.3s)  run_id=954d98c3ae28
Epoch: [0]  [ 0/39]  eta: 0:00:21  lr: 0.0001  img/s: 239.88827187082777  loss: 0.1729 (0.1729)  acc1: 94.5312 (94.5312)  acc5: 100.0000 (100.0000)  time: 0.5406  data: 0.0070
Epoch: [0] Total time: 0:00:18
Epoch: [1]  [ 0/39]  eta: 0:00:19  lr: 0.0001  img/s: 260.9932339343617  loss: 0.1679 (0.1679)  acc1: 95.3125 (95.3125)  acc5: 100.0000 (100.0000)  time: 0.4972  data: 0.0067
Epoch: [1] Total time: 0:00:18
Epoch: [2]  [ 0/39]  eta: 0:00:19  lr: 0.0001  img/s: 265.70191470155044  loss: 0.1605 (0.1605)  acc1: 95.3125 (95.3125)  acc5: 100.0000 (100.0000)  time: 0.4923  data: 0.0105
Epoch: [2] Total time: 0:00:18

  retrained(3ep) top1=89.2228  top5=99.3690  (24.7s)  run_id=5a2bc65d01dc

=== cifar10 / resnet20 / mul8s_1kvb ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
Creating extension directory /root/.cache/torch_extensions/py310_cpu/PyInit_conv2d_mul8s_1kvb...
Emitting ninja build file /root/.cache/torch_extensions/py310_cpu/PyInit_conv2d_mul8s_1kvb/build.ninja...
Building extension module PyInit_conv2d_mul8s_1kvb...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)

[1/2] c++ -MMD -MF axx_conv2d.o.d -DTORCH_EXTENSION_NAME=PyInit_conv2d_mul8s_1kvb -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /usr/local/lib/python3.10/dist-packages/torch/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.10/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.10/dist-packages/torch/include/THC -isystem /usr/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DAXX_MULT=mul8s_1kvb -march=native -fopenmp -O3 -c /workspace/adapt/adapt/cpu-kernels/axx_conv2d.cpp -o axx_conv2d.o
[2/2] c++ axx_conv2d.o -shared -lgomp -L/usr/local/lib/python3.10/dist-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o PyInit_conv2d_mul8s_1kvb.so

Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
W0626 17:53:33.652842 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.653333 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.653549 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.653739 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.653924 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.654100 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.654281 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.654440 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.654610 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.654770 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.654936 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.655391 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.655541 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.655681 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.655839 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.656112 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.656247 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.656377 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.656509 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.656641 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.656773 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.656905 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.657034 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.657163 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.657294 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.657448 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.657600 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.657731 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.657870 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658003 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658132 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658252 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658392 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658526 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658663 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658797 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.658936 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.659067 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.659202 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.659344 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.659483 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.659640 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:53:33.660821 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.661108 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.661355 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.661614 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.661867 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.662096 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.662325 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.662542 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.662816 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.663118 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.663441 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.663703 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.663942 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.664168 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.664393 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.664615 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.664844 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.665062 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.665284 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.665503 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.665737 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.665964 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.666191 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.666414 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.666646 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.666887 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.667166 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.667401 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.667635 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.667855 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.668076 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.668290 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.668512 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.668841 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.669090 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.669310 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.669536 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.669806 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.670060 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.670285 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.670515 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 17:53:33.670741 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).

  eval-only      top1=90.0641  top5=99.6494  (25.1s)  run_id=c3c9816dbb94
Epoch: [0]  [ 0/39]  eta: 0:00:20  lr: 0.0001  img/s: 244.63514716724583  loss: 0.1697 (0.1697)  acc1: 94.5312 (94.5312)  acc5: 100.0000 (100.0000)  time: 0.5314  data: 0.0081
Epoch: [0] Total time: 0:00:19
Epoch: [1]  [ 0/39]  eta: 0:00:20  lr: 0.0001  img/s: 254.62642823096422  loss: 0.1591 (0.1591)  acc1: 95.3125 (95.3125)  acc5: 100.0000 (100.0000)  time: 0.5150  data: 0.0123
Epoch: [1] Total time: 0:00:19
Epoch: [2]  [ 0/39]  eta: 0:00:20  lr: 0.0001  img/s: 250.26205147687782  loss: 0.1502 (0.1502)  acc1: 96.0938 (96.0938)  acc5: 100.0000 (100.0000)  time: 0.5232  data: 0.0117
Epoch: [2] Total time: 0:00:19

  retrained(3ep) top1=89.2628  top5=99.3289  (25.6s)  run_id=1157b475df71
[skip] cifar10/resnet20/mul8s_1l2h — both rows present
[skip] cifar10/resnet20/mul8s_fpga_ish_1 — both rows present
[skip] cifar10/resnet20/mul8s_fpga_ish_2 — both rows present
[skip] cifar10/resnet20/mul8s_fpga_ish_3 — both rows present
[skip] cifar10/resnet20/mul8s_fpga_ish_4 — both rows present
[skip] cifar10/resnet20/mul8s_fpga_ish_5 — both rows present
[skip] cifar10/resnet20/mul8s_acc — both rows present

=== cifar10 / resnet56 / mul8s_1kva ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
W0626 17:55:23.323467 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.323851 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.324133 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.324410 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.324677 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.324887 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.325123 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.325390 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.325711 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.325993 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.326275 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.326567 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.326848 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.327154 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.327447 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.327751 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.328039 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.328311 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.328585 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.328875 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.329151 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.329429 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.329712 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.329995 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.330262 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.330545 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.330831 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.331125 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.331423 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.331708 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.332014 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.332298 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.332566 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.332867 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.333163 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.333443 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.333734 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.334012 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.334305 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.334625 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.334952 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.335253 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.335533 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.335832 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.336156 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.336473 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.336795 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.337075 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.337384 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.337673 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.337970 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.338258 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.338537 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.338821 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.339110 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.341423 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.341701 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.341958 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.342243 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.342563 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.342887 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.343186 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.343400 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.343559 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.343748 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.343896 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.344064 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.344219 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.344376 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.344524 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 17:55:23.344680 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator

  eval-only      top1=93.9804  top5=99.7696  (72.7s)  run_id=1430c3230807
Epoch: [0]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 89.18168867342817  loss: 0.0697 (0.0697)  acc1: 96.8750 (96.8750)  acc5: 100.0000 (100.0000)  time: 1.4430  data: 0.0077
Epoch: [0] Total time: 0:00:54
Epoch: [1]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 89.63507781427487  loss: 0.0668 (0.0668)  acc1: 96.8750 (96.8750)  acc5: 100.0000 (100.0000)  time: 1.4405  data: 0.0124
Epoch: [1] Total time: 0:00:54
Epoch: [2]  [ 0/39]  eta: 0:00:54  lr: 0.0001  img/s: 92.10553474628946  loss: 0.0640 (0.0640)  acc1: 96.8750 (96.8750)  acc5: 100.0000 (100.0000)  time: 1.3973  data: 0.0076
Epoch: [2] Total time: 0:00:54

  retrained(3ep) top1=91.7668  top5=99.5693  (72.6s)  run_id=6f0648e0e6c3

=== cifar10 / resnet56 / mul8s_1kvb ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
W0626 18:00:34.529420 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.530094 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.530588 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.530869 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.531246 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.531460 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.531678 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.531875 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.532133 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.532365 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.532640 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.533135 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.533334 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.533692 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.533984 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.534267 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.534529 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.534795 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.535038 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.535263 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.535482 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.535708 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.536239 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.536449 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.536682 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.536884 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.537087 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.537267 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.537440 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.537621 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.537809 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.537975 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.538142 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.538314 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.538479 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.538660 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.538827 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.538992 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.539219 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.539447 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.540227 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.540523 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.540828 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.541035 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.541241 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.541506 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.542012 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.542200 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.542380 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.542568 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.542783 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.542948 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.543107 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.543250 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.543661 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.543797 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.543940 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.544083 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.544216 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.544550 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.544718 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.544880 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.545041 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.545219 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.545387 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.545538 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.545685 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.545831 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.546004 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.546201 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:00:34.546363 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator

  eval-only      top1=92.5080  top5=99.7296  (73.2s)  run_id=8cee1be38da1
Epoch: [0]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 88.60380335392395  loss: 0.0673 (0.0673)  acc1: 96.8750 (96.8750)  acc5: 100.0000 (100.0000)  time: 1.4530  data: 0.0083
Epoch: [0] Total time: 0:00:54
Epoch: [1]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 89.71963676368131  loss: 0.0646 (0.0646)  acc1: 96.8750 (96.8750)  acc5: 100.0000 (100.0000)  time: 1.4396  data: 0.0129
Epoch: [1] Total time: 0:00:54
Epoch: [2]  [ 0/39]  eta: 0:00:55  lr: 0.0001  img/s: 89.91574560420659  loss: 0.0631 (0.0631)  acc1: 96.8750 (96.8750)  acc5: 100.0000 (100.0000)  time: 1.4324  data: 0.0088
Epoch: [2] Total time: 0:00:54

  retrained(3ep) top1=91.8269  top5=99.5693  (72.9s)  run_id=d167a352348f
[skip] cifar10/resnet56/mul8s_1l2h — both rows present
[skip] cifar10/resnet56/mul8s_fpga_ish_1 — both rows present
[skip] cifar10/resnet56/mul8s_fpga_ish_2 — both rows present
[skip] cifar10/resnet56/mul8s_fpga_ish_3 — both rows present
[skip] cifar10/resnet56/mul8s_fpga_ish_4 — both rows present
[skip] cifar10/resnet56/mul8s_fpga_ish_5 — both rows present
[skip] cifar10/resnet56/mul8s_acc — both rows present

=== cifar10 / vgg11_bn / mul8s_1kva ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
W0626 18:05:46.476413 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.476955 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.477150 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.477327 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.477737 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.477932 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.478106 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.478253 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.478391 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.478523 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.478661 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.478791 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.478940 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.479081 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.479216 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.479381 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:05:46.480014 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.480261 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.480558 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.480787 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.481013 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.481329 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.481586 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.481867 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.482113 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.482336 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.482690 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.483052 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.483389 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.483708 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.484022 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:05:46.484333 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).

  eval-only      top1=91.7368  top5=99.6494  (69.0s)  run_id=2ad9332db07a
Epoch: [0]  [ 0/39]  eta: 0:00:51  lr: 0.0001  img/s: 97.16809289548551  loss: 0.0169 (0.0169)  acc1: 99.2188 (99.2188)  acc5: 100.0000 (100.0000)  time: 1.3265  data: 0.0092
Epoch: [0] Total time: 0:00:43
Epoch: [1]  [ 0/39]  eta: 0:00:43  lr: 0.0001  img/s: 115.86070065747874  loss: 0.0080 (0.0080)  acc1: 100.0000 (100.0000)  acc5: 100.0000 (100.0000)  time: 1.1184  data: 0.0136
Epoch: [1] Total time: 0:00:42
Epoch: [2]  [ 0/39]  eta: 0:00:44  lr: 0.0001  img/s: 114.55971116329538  loss: 0.0067 (0.0067)  acc1: 100.0000 (100.0000)  acc5: 100.0000 (100.0000)  time: 1.1301  data: 0.0127
Epoch: [2] Total time: 0:00:42

  retrained(3ep) top1=91.3462  top5=99.5393  (68.5s)  run_id=b1befb7fe19f

=== cifar10 / vgg11_bn / mul8s_1kvb ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
W0626 18:10:13.528634 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.529125 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.529452 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.529774 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.530155 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.530378 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.530612 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.530790 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.530967 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.531143 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.531314 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.531479 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.531653 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.531833 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.531996 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.532159 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:10:13.532861 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.533185 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.533515 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.533865 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.534170 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.534460 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.534761 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.535053 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.535389 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.535692 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.536000 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.536316 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.536629 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.537010 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.537339 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:10:13.537652 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).

  eval-only      top1=89.7135  top5=99.3790  (68.5s)  run_id=ffa223a00f80
Epoch: [0]  [ 0/39]  eta: 0:00:43  lr: 0.0001  img/s: 116.21450346400326  loss: 0.0119 (0.0119)  acc1: 99.2188 (99.2188)  acc5: 100.0000 (100.0000)  time: 1.1090  data: 0.0075
Epoch: [0] Total time: 0:00:42
Epoch: [1]  [ 0/39]  eta: 0:00:42  lr: 0.0001  img/s: 117.03352061745775  loss: 0.0124 (0.0124)  acc1: 99.2188 (99.2188)  acc5: 100.0000 (100.0000)  time: 1.1009  data: 0.0072
Epoch: [1] Total time: 0:00:42
Epoch: [2]  [ 0/39]  eta: 0:00:43  lr: 0.0001  img/s: 115.90309725658113  loss: 0.0100 (0.0100)  acc1: 100.0000 (100.0000)  acc5: 100.0000 (100.0000)  time: 1.1149  data: 0.0106
Epoch: [2] Total time: 0:00:42

  retrained(3ep) top1=91.3161  top5=99.5693  (68.3s)  run_id=1c4280ce550a
[skip] cifar10/vgg11_bn/mul8s_1l2h — both rows present
[skip] cifar10/vgg11_bn/mul8s_fpga_ish_1 — both rows present
[skip] cifar10/vgg11_bn/mul8s_fpga_ish_2 — both rows present
[skip] cifar10/vgg11_bn/mul8s_fpga_ish_3 — both rows present
[skip] cifar10/vgg11_bn/mul8s_fpga_ish_4 — both rows present
[skip] cifar10/vgg11_bn/mul8s_fpga_ish_5 — both rows present
[skip] cifar10/vgg11_bn/mul8s_acc — both rows present
Files already downloaded and verified
Files already downloaded and verified

=== cifar100 / resnet20 / mul8s_1kva ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
W0626 18:14:39.785169 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.785789 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.786642 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.786923 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.787157 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.787428 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.787678 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.787882 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.788068 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.788275 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.788456 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.788641 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.788835 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.789000 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.789167 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.789333 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.789494 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.789656 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.789819 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.789980 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.790139 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.790286 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.790434 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.790576 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.790729 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.790870 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.791026 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.791215 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.791366 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.791498 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.791649 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.791782 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.791917 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792048 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792181 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792311 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792444 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792576 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792709 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792834 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.792964 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.793094 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:14:39.794566 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.794829 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.795062 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.795275 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.795483 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.795690 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.795895 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.796108 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.796313 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.796514 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.796722 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.796924 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.797137 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.797347 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.797554 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.797760 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.797968 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.798168 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.798389 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.798602 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.798821 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.799037 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.799253 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.799493 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.799721 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.799934 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.800162 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.800368 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.800579 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.800786 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.800995 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.801200 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.801401 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.801600 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.801803 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.802013 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.802224 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.802429 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.802636 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.802841 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.803045 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:14:39.803299 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).

  eval-only      top1=67.7985  top5=90.7652  (24.9s)  run_id=fd761be3deb7
Epoch: [0]  [ 0/39]  eta: 0:00:19  lr: 0.0001  img/s: 256.6045738216652  loss: 0.8068 (0.8068)  acc1: 79.6875 (79.6875)  acc5: 92.9688 (92.9688)  time: 0.5064  data: 0.0076
Epoch: [0] Total time: 0:00:19
Epoch: [1]  [ 0/39]  eta: 0:00:20  lr: 0.0001  img/s: 251.0674860511805  loss: 0.7938 (0.7938)  acc1: 80.4688 (80.4688)  acc5: 92.9688 (92.9688)  time: 0.5175  data: 0.0077
Epoch: [1] Total time: 0:00:19
Epoch: [2]  [ 0/39]  eta: 0:00:19  lr: 0.0001  img/s: 255.0865231566874  loss: 0.7795 (0.7795)  acc1: 80.4688 (80.4688)  acc5: 92.9688 (92.9688)  time: 0.5092  data: 0.0074
Epoch: [2] Total time: 0:00:19

  retrained(3ep) top1=62.7804  top5=86.9792  (24.9s)  run_id=5bccb132fef8

=== cifar100 / resnet20 / mul8s_1kvb ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
W0626 18:16:27.995108 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.995602 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.995924 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.996212 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.996459 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.996743 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.997005 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.997284 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.997558 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.997876 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.998168 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.998414 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.998687 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.998938 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.999188 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.999409 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.999635 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:27.999861 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.000076 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.000272 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.000490 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.000691 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.000884 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.001066 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.002083 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.002269 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.002426 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.002577 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.002739 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.002892 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.003042 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.003213 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.003372 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.003525 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.003684 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.003834 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.003971 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.004131 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.004284 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.004443 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.004598 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.004754 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:16:28.005707 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.006059 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.006363 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.006648 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.006928 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.007194 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.007465 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.007747 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.008024 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.008280 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.008545 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.008803 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.009080 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.009338 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.009599 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.009876 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.010157 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.010421 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.010688 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.010942 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.011206 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.011480 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.011752 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.011960 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.012271 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.012544 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.012840 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.013105 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.013367 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.013630 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.013866 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.014196 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.014466 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.014735 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.015013 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.015273 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.015538 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.015795 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.016057 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.016328 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.016596 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:16:28.016923 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).

  eval-only      top1=61.2881  top5=86.6587  (25.1s)  run_id=bcfae1b713db
Epoch: [0]  [ 0/39]  eta: 0:00:20  lr: 0.0001  img/s: 245.51413371893352  loss: 0.8069 (0.8069)  acc1: 79.6875 (79.6875)  acc5: 93.7500 (93.7500)  time: 0.5289  data: 0.0076
Epoch: [0] Total time: 0:00:19
Epoch: [1]  [ 0/39]  eta: 0:00:19  lr: 0.0001  img/s: 256.1183408128012  loss: 0.7860 (0.7860)  acc1: 80.4688 (80.4688)  acc5: 93.7500 (93.7500)  time: 0.5078  data: 0.0080
Epoch: [1] Total time: 0:00:19
Epoch: [2]  [ 0/39]  eta: 0:00:19  lr: 0.0001  img/s: 256.9934644777877  loss: 0.7761 (0.7761)  acc1: 82.0312 (82.0312)  acc5: 93.7500 (93.7500)  time: 0.5061  data: 0.0081
Epoch: [2] Total time: 0:00:19

  retrained(3ep) top1=62.9307  top5=86.8389  (24.8s)  run_id=4a2e3865e454
[skip] cifar100/resnet20/mul8s_1l2h — both rows present
[skip] cifar100/resnet20/mul8s_fpga_ish_1 — both rows present
[skip] cifar100/resnet20/mul8s_fpga_ish_2 — both rows present
[skip] cifar100/resnet20/mul8s_fpga_ish_3 — both rows present
[skip] cifar100/resnet20/mul8s_fpga_ish_4 — both rows present
[skip] cifar100/resnet20/mul8s_fpga_ish_5 — both rows present
[skip] cifar100/resnet20/mul8s_acc — both rows present

=== cifar100 / resnet56 / mul8s_1kva ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
W0626 18:18:17.199656 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.200213 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.200992 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.201209 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.201423 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.201588 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.201769 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.201910 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.202043 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.202165 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.202306 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.202432 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.202568 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.202908 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.203230 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.203563 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.203863 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.204152 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.204416 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.204671 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.204918 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.205173 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.205421 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.205707 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.206019 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.206292 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.206614 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.206880 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.207141 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.207399 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.207679 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.207922 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.208134 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.208290 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.208449 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.208582 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.208723 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.208846 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.208991 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.209123 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.209256 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.210514 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.210673 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.210901 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.211053 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.211189 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.211323 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.211457 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.211586 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.211750 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.211895 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.212031 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.212170 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.212310 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.212445 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.212585 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.212733 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.212875 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.213024 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.213169 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.213314 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.213453 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.213621 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.213767 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.213906 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.214051 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.214198 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.214353 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.215296 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.215453 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:18:17.215618 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator

  eval-only      top1=71.8950  top5=91.7869  (74.2s)  run_id=ee25f8d0f738
Epoch: [0]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 89.40247832634289  loss: 0.4053 (0.4053)  acc1: 87.5000 (87.5000)  acc5: 96.0938 (96.0938)  time: 1.4392  data: 0.0075
Epoch: [0] Total time: 0:00:55
Epoch: [1]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 89.22160147242731  loss: 0.3784 (0.3784)  acc1: 87.5000 (87.5000)  acc5: 96.0938 (96.0938)  time: 1.4467  data: 0.0120
Epoch: [1] Total time: 0:00:55
Epoch: [2]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 89.16110153224571  loss: 0.3605 (0.3605)  acc1: 89.0625 (89.0625)  acc5: 96.8750 (96.8750)  time: 1.4537  data: 0.0180
Epoch: [2] Total time: 0:00:55

  retrained(3ep) top1=67.6883  top5=87.9708  (74.4s)  run_id=c2f2c497ff82

=== cifar100 / resnet56 / mul8s_1kvb ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
W0626 18:23:34.289595 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.290587 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.290962 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.291474 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.291776 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.292116 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.292559 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.292861 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.293118 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.293349 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.293584 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.293823 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.294067 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.294473 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.294863 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.295222 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.295488 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.295716 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.295929 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.296118 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.296305 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.296478 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.296663 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.296857 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.297046 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.297241 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.297433 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.297621 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.297804 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.297981 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.298165 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.298335 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.298501 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.298663 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.298817 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.298949 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.299075 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.299205 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.299341 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.299472 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.299599 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.299741 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.299880 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.300028 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.300223 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.300419 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.300596 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.300755 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.300915 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.301064 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.301215 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.301356 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.301522 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.301665 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.301800 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.301930 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302061 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302187 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302308 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302445 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302577 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302713 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302843 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.302970 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.303098 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.303220 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.303359 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.303487 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.303619 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.303749 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:23:34.303882 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator

  eval-only      top1=66.0156  top5=88.2913  (74.7s)  run_id=874dff6719ff
Epoch: [0]  [ 0/39]  eta: 0:00:57  lr: 0.0001  img/s: 87.81533604803035  loss: 0.3849 (0.3849)  acc1: 88.2812 (88.2812)  acc5: 96.0938 (96.0938)  time: 1.4651  data: 0.0075
Epoch: [0] Total time: 0:00:55
Epoch: [1]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 88.98227567304261  loss: 0.3633 (0.3633)  acc1: 89.0625 (89.0625)  acc5: 96.0938 (96.0938)  time: 1.4464  data: 0.0079
Epoch: [1] Total time: 0:00:55
Epoch: [2]  [ 0/39]  eta: 0:00:56  lr: 0.0001  img/s: 89.41008661707127  loss: 0.3445 (0.3445)  acc1: 89.0625 (89.0625)  acc5: 97.6562 (97.6562)  time: 1.4395  data: 0.0079
Epoch: [2] Total time: 0:00:55

  retrained(3ep) top1=67.5381  top5=87.9107  (74.2s)  run_id=752c04d39f9d
[skip] cifar100/resnet56/mul8s_1l2h — both rows present
[skip] cifar100/resnet56/mul8s_fpga_ish_1 — both rows present
[skip] cifar100/resnet56/mul8s_fpga_ish_2 — both rows present
[skip] cifar100/resnet56/mul8s_fpga_ish_3 — both rows present
[skip] cifar100/resnet56/mul8s_fpga_ish_4 — both rows present
[skip] cifar100/resnet56/mul8s_fpga_ish_5 — both rows present
[skip] cifar100/resnet56/mul8s_acc — both rows present

=== cifar100 / vgg11_bn / mul8s_1kva ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kva, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kva...
W0626 18:28:50.988112 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.988484 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.988683 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.988842 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.988985 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.989125 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.989456 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.989715 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.989959 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.990195 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.990432 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.990666 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.990900 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.991117 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.991329 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.991557 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:28:50.992521 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.993104 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.993522 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.993938 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.994411 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.994872 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.995333 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.995783 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.996266 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.996750 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.997218 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.997577 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.998104 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.998629 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.999151 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:28:50.999640 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).

  eval-only      top1=70.0020  top5=88.3413  (70.4s)  run_id=db7e5edb616d
Epoch: [0]  [ 0/39]  eta: 0:00:43  lr: 0.0001  img/s: 115.57954408945123  loss: 0.0619 (0.0619)  acc1: 99.2188 (99.2188)  acc5: 100.0000 (100.0000)  time: 1.1149  data: 0.0074
Epoch: [0] Total time: 0:00:43
Epoch: [1]  [ 0/39]  eta: 0:00:45  lr: 0.0001  img/s: 111.9213451969299  loss: 0.0482 (0.0482)  acc1: 99.2188 (99.2188)  acc5: 99.2188 (99.2188)  time: 1.1564  data: 0.0127
Epoch: [1] Total time: 0:00:43
Epoch: [2]  [ 0/39]  eta: 0:00:44  lr: 0.0001  img/s: 112.44721606325032  loss: 0.0480 (0.0480)  acc1: 99.2188 (99.2188)  acc5: 99.2188 (99.2188)  time: 1.1457  data: 0.0073
Epoch: [2] Total time: 0:00:43

  retrained(3ep) top1=68.1991  top5=86.7588  (70.4s)  run_id=3be6ae0aa718

=== cifar100 / vgg11_bn / mul8s_1kvb ===

Using cache found in /root/.cache/torch/hub/chenyaofo_pytorch-cifar-models_master
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
Using /root/.cache/torch_extensions/py310_cpu as PyTorch extensions root...
No modifications detected for re-loaded extension module PyInit_conv2d_mul8s_1kvb, skipping build step...
Loading extension module PyInit_conv2d_mul8s_1kvb...
W0626 18:33:23.475627 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.476092 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.476288 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.476445 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.476591 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.476853 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.476999 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.477134 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.477264 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.477400 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.477531 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.477670 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.477796 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.477931 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.478068 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.478196 124414754996224 tensor_quantizer.py:174] Disable HistogramCalibrator
W0626 18:33:23.478774 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.479004 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.479214 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.479420 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.479628 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.479826 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.480033 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.480232 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.480435 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.480639 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.480916 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.481157 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.481368 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.481570 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.481782 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).
W0626 18:33:23.481982 124414754996224 tensor_quantizer.py:238] Load calibrated amax, shape=torch.Size([]).

  eval-only      top1=63.4215  top5=83.6639  (70.7s)  run_id=6aafa7d8b1bc
Epoch: [0]  [ 0/39]  eta: 0:00:43  lr: 0.0001  img/s: 114.87636737351521  loss: 0.0406 (0.0406)  acc1: 98.4375 (98.4375)  acc5: 100.0000 (100.0000)  time: 1.1234  data: 0.0092
Epoch: [0] Total time: 0:00:43
Epoch: [1]  [ 0/39]  eta: 0:00:43  lr: 0.0001  img/s: 115.16898021770669  loss: 0.0525 (0.0525)  acc1: 98.4375 (98.4375)  acc5: 100.0000 (100.0000)  time: 1.1186  data: 0.0072
Epoch: [1] Total time: 0:00:43
Epoch: [2]  [ 0/39]  eta: 0:00:43  lr: 0.0001  img/s: 116.72251170712607  loss: 0.0574 (0.0574)  acc1: 99.2188 (99.2188)  acc5: 100.0000 (100.0000)  time: 1.1071  data: 0.0105
Epoch: [2] Total time: 0:00:43

  retrained(3ep) top1=67.7885  top5=86.5284  (70.4s)  run_id=b5c7739d8ca9
[skip] cifar100/vgg11_bn/mul8s_1l2h — both rows present
[skip] cifar100/vgg11_bn/mul8s_fpga_ish_1 — both rows present
[skip] cifar100/vgg11_bn/mul8s_fpga_ish_2 — both rows present
[skip] cifar100/vgg11_bn/mul8s_fpga_ish_3 — both rows present
[skip] cifar100/vgg11_bn/mul8s_fpga_ish_4 — both rows present
[skip] cifar100/vgg11_bn/mul8s_fpga_ish_5 — both rows present
[skip] cifar100/vgg11_bn/mul8s_acc — both rows present
Done.
Results saved under: /work/results/adapt

  runs.csv                                147 rows -- one per (dataset, model, multiplier, retrained/not)
  confusion_matrices/<dataset>/<..>.npy   147 files  -- per-run confusion matrix (loaded by 3_multiplier_deepdive.ipynb)

Open the results CSV:

/work/results/adapt/runs.csv

,run_id,timestamp,dataset,model,multiplier,retrained_epochs,top1,top5,n_samples,runtime_s,notes
132,b1befb7fe19f,2026-06-26T18:10:12,cifar10,vgg11_bn,mul8s_1kva,3,91.3462,99.5393,9984,68.5,NaN
133,ffa223a00f80,2026-06-26T18:11:22,cifar10,vgg11_bn,mul8s_1kvb,0,89.7135,99.3790,9984,68.5,NaN
134,1c4280ce550a,2026-06-26T18:14:37,cifar10,vgg11_bn,mul8s_1kvb,3,91.3161,99.5693,9984,68.3,NaN
135,fd761be3deb7,2026-06-26T18:15:04,cifar100,resnet20,mul8s_1kva,0,67.7985,90.7652,9984,24.9,NaN
136,5bccb132fef8,2026-06-26T18:16:26,cifar100,resnet20,mul8s_1kva,3,62.7804,86.9792,9984,24.9,NaN
137,bcfae1b713db,2026-06-26T18:16:53,cifar100,resnet20,mul8s_1kvb,0,61.2881,86.6587,9984,25.1,NaN
138,4a2e3865e454,2026-06-26T18:18:15,cifar100,resnet20,mul8s_1kvb,3,62.9307,86.8389,9984,24.8,NaN
139,ee25f8d0f738,2026-06-26T18:19:31,cifar100,resnet56,mul8s_1kva,0,71.8950,91.7869,9984,74.2,NaN
140,c2f2c497ff82,2026-06-26T18:23:32,cifar100,resnet56,mul8s_1kva,3,67.6883,87.9708,9984,74.4,NaN
141,874dff6719ff,2026-06-26T18:24:49,cifar100,resnet56,mul8s_1kvb,0,66.0156,88.2913,9984,74.7,NaN
142,752c04d39f9d,2026-06-26T18:28:50,cifar100,resnet56,mul8s_1kvb,3,67.5381,87.9107,9984,74.2,NaN
143,db7e5edb616d,2026-06-26T18:30:01,cifar100,vgg11_bn,mul8s_1kva,0,70.0020,88.3413,9984,70.4,NaN
144,3be6ae0aa718,2026-06-26T18:33:22,cifar100,vgg11_bn,mul8s_1kva,3,68.1991,86.7588,9984,70.4,NaN
145,6aafa7d8b1bc,2026-06-26T18:34:34,cifar100,vgg11_bn,mul8s_1kvb,0,63.4215,83.6639,9984,70.7,NaN
146,b5c7739d8ca9,2026-06-26T18:37:55,cifar100,vgg11_bn,mul8s_1kvb,3,67.7885,86.5284,9984,70.4,NaN